apiVersion: v1
kind: Service
metadata:
  name: myapp1
  labels:
    app: myapp1
    env: demo   
spec:
  type: NodePort
  selector:
    app: myapp1
  ports:
  - nodePort: 30001
    port: 80
    name: http
    targetPort: 80