apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo Hello from the container && sleep 3600']
    env:
    - name: FIRSTNAME
      value: "Amit"
    - name: LASTNAME
      value: "Kumar"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  initContainers:
    - name: init-container
      image: busybox:1.28
      command: ['sh', '-c', 'echo Hello from the init container']
      args: ['until nslookup myservcie.default.svc.cluster.local']
    - name: init-mydb
      image: busybox:1.28
      command: ['sh', '-c', 'echo Hello from the init container']
      args: ['until nslookup mydb.default.svc.cluster.local']