apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp1
  selector:
    matchLabels:
      env: demo
    app: myapp1
spec:
  template:
    metadata:
      name: myapp1
      labels:
        app: myapp1
        env: demo
    spec:
      containers:
        - name: myapp1
          image: nginx
          ports:
            - containerPort: 80